set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
set(LLVM_MINGW_PATH "/opt/llvm-mingw")

set(CMAKE_C_COMPILER ${LLVM_MINGW_PATH}/bin/${TOOLCHAIN_PREFIX}-clang)
set(CMAKE_CXX_COMPILER ${LLVM_MINGW_PATH}/bin/${TOOLCHAIN_PREFIX}-clang++)
set(CMAKE_RC_COMPILER ${LLVM_MINGW_PATH}/bin/${TOOLCHAIN_PREFIX}-windres)

set(CMAKE_FIND_ROOT_PATH ${LLVM_MINGW_PATH}/${TOOLCHAIN_PREFIX})

# Add vcpkg installation directory to search path for cross-compilation
if(DEFINED VCPKG_INSTALLED_DIR)
    list(APPEND CMAKE_FIND_ROOT_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
